---
#This Playbook creates user in target machines

- name: Create a new user
  hosts: all
  become: yes
  vars:
    user_name: "newuser"
    user_password: "{{ 'securepassword' | password_hash('sha512') }}"
    user_groups: "sudo"
    user_shell: "/bin/bash"
  tasks:
    - name: Ensure the user is present
      user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        groups: "{{ user_groups }}"
        shell: "{{ user_shell }}"
        state: present

    - name: Create a home directory for the user
      file:
        path: "/home/{{ user_name }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'

    - name: Set up SSH directory for the user
      file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0700'

    - name: Add authorized key for the user
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD3x8v3..."
