---
#This playbook enables firewall and port

- name: Security Hardening
  hosts: all
  become: yes
  tasks:
    - name: Ensure firewall is installed
      apt:
        name: ufw
        state: present

    - name: Allow SSH
      ufw:
        rule: allow
        port: 22

    - name: Enable UFW
      ufw:
        state: enabled
