---
# tasks file for apache

# tasks/main.yml

- name: Update the package repository cache
  apt:
    update_cache: yes
  become: true

- name: Install Apache
  apt:
    name: apache2
    state: present
  become: true

- name: Ensure Apache is started
  service:
    name: apache2
    state: started
    enabled: true
  become: true

- name: Copy index.html to web server
  copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true

- name: Open firewall port for Apache
  ufw:
    rule: allow
    port: "{{ apache_port }}"
    proto: tcp
  become: true

- name: Allow SSH port through firewall
  ufw:
    rule: allow
    port: 22
    proto: tcp
  become: true

